'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'RestaurantDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'QuadratTouch', :git => 'https://github.com/Constantine-Fry/das-quadrat', :branch => 'fry-swift30'
  pod 'SDWebImage', '~>3.8'
  # Pods for RestaurantDemo

  target 'RestaurantDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RestaurantDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
